name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install DOSBox
      run: sudo apt-get install -y dosbox
    - name: Download Turbo C++
      run: |
        wget -O tc3.zip "https://github.com/vineetchoudhary/turbocpp/releases/download/v3.2/Turbo.C.3.2.zip?raw=true"
        unzip tc3.zip -d $HOME/tc
        mkdir -p $HOME/.dosbox
        echo -e "[autoexec]\nmount c ~\nc:\ncd tc\ncd bin\n" > $HOME/.dosbox/dosbox-0.74.conf
    - name: Build and Run in DOSBox
      run: |
        mkdir -p $HOME/tc/bin
        echo -e "tc.exe AKHIL.cpp" > $HOME/tc/bin/compile.bat
        dosbox $HOME/tc/bin/compile.bat -c "exit"
